version: '3'
services:
    estoque:
        build:
            context: estoque
            dockerfile: Dockerfile
        container_name: estoque-execucao
        expose:
            - 8080
        ports:
            - 8090:8080
        command: java -jar estoque.jar
        image: estoque-imagem
    pedido:
        build:
            context: pedido-service
            dockerfile: Dockerfile
        container_name: pedido-execucao
        ports:
            - 8091:8080
        command: java -jar pedidos.jar
        image: pedido-imagem
        environment:
            - URL_TO_ESTOQUE_SERVICE=http://estoque:8080/api/produtos/
            - AMBIENTE_EXECUCAO=Container
    prometheus:
        build:
            context: prometheus
            dockerfile: Dockerfile
        container_name: prometheus-execucao
        ports:
            - 9090:9090
        image: prometheus-imagem
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
  
            
